# Generated by Django 5.2.4 on 2025-07-17 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0003_remove_message_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OCRDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='ocr_uploads/')),
                ('filename', models.CharField(max_length=255)),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('extracted_data', models.JSONField(blank=True, null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('tags', models.CharField(blank=True, max_length=255, null=True)),
                ('chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocr_documents', to='chat.chat')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocr_documents', to='chat.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
